# Generated by ChatGPT on 2026-01-27

from django.db import migrations


def rename_model_id_column(apps, schema_editor):
    table = 'jobs_job'
    with schema_editor.connection.cursor() as cursor:
        columns = [c.name for c in schema_editor.connection.introspection.get_table_description(cursor, table)]
    if 'model_id' in columns:
        schema_editor.execute(f'ALTER TABLE {table} RENAME COLUMN model_id TO model')


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_artifact_job_kind_idx_jobs_artifa_job_id_e21ea2_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_model_id_column, migrations.RunPython.noop),
    ]
